"use client";
import{useMemo,useState}from"react";
import{AlertTriangle,Check,Clock3,FileCheck2,Paperclip,ShieldCheck,X}from"lucide-react";
import Attachments from"./Attachments";
type Payment={id:number;requestNo:string;company:string;vendor:string;amount:number;currency:string;due:string;urgency:string;status:string;owner:string;department:string};
const stages=["Requested","Accounts","Audit","Correction","Recheck","Release"];
export default function PaymentDetail({payment:p,role,onClose,onAction}:{payment:Payment;role:string;onClose:()=>void;onAction:(s:string)=>void}){
 const accountQueue=["Submitted","Requested"].includes(p.status),accountWork=["Accountant Accepted","Accountant Review"].includes(p.status),auditQueue=p.status==="Pre-Audit Queue",auditWork=p.status==="Audit Accepted",correction=p.status==="Observation – Accounts Action",recheck=p.status==="Audit Reconfirmation",approved=p.status==="Approved by Auditor – Ready to Release",released=p.status==="Payment Released";
 const[checks,setChecks]=useState<Record<string,boolean>>({}),[observation,setObservation]=useState("Supporting documents do not reconcile with the ledger balance."),[proof,setProof]=useState("");
 const active=useMemo(()=>released?5:approved?5:recheck?4:correction?3:auditWork||auditQueue?2:accountWork||accountQueue?1:0,[p.status]);
 /* Each stage belongs to one role. An administrator or audit head may also act, so a
    request is never stuck because the responsible person is unavailable. */
 const can=(r:string)=>role===r||role==="Administrator"||role==="Audit Head";
 const reject=(reason:string)=>{if(confirm(reason))onAction("Rejected")};
 const toggle=(k:string)=>setChecks(v=>({...v,[k]:!v[k]})),complete=(ks:string[])=>ks.every(k=>checks[k]);
 const accountKeys=["PO / Invoice / DO matched","Balance reconciled"],auditKeys=["Documents verified","GL posting correct","Balance reconciled"];
 const list=(ks:string[])=><div className="wf-checks">{ks.map(k=><label key={k} className={checks[k]?"done":""}><input type="checkbox" checked={!!checks[k]} onChange={()=>toggle(k)}/><span>{checks[k]?<Check/>:null}</span><b>{k}</b></label>)}</div>;
 let action=<div className="wf-callout"><Clock3/>This request is visible to you. Switch to its responsible role to perform the next action.</div>;
 if(accountQueue&&can("Accountant"))action=<><div className="wf-callout"><Clock3/>Available in the common Accounts queue.</div><div className="wf-actions"><button className="wf-reject" onClick={()=>reject("Reject this request and send it back to the requestor?")}><X/>Reject</button><button className="wf-primary" onClick={()=>onAction("Accountant Accepted")}><Check/>Accept to Start</button></div></>;
 if(accountWork&&can("Accountant"))action=<>{list(accountKeys)}<label className="wf-note">Issues fixed / accountant note<textarea placeholder="Record issues and how they were fixed"/></label><button className="wf-primary" disabled={!complete(accountKeys)} onClick={()=>onAction("Pre-Audit Queue")}>Send to Audit</button></>;
 if(auditQueue&&can("Auditor"))action=<><div className="wf-callout"><ShieldCheck/>Available in the common Audit queue.</div><div className="wf-actions"><button className="wf-reject" onClick={()=>reject("Reject this request at audit and send it back?")}><X/>Reject</button><button className="wf-primary" onClick={()=>onAction("Audit Accepted")}><Check/>Accept to Start</button></div></>;
 if(auditWork&&can("Auditor"))action=<>{list(auditKeys)}<label className="wf-note">Audit observation<textarea value={observation} onChange={e=>setObservation(e.target.value)}/></label><div className="wf-actions"><button className="wf-reject" onClick={()=>onAction("Observation – Accounts Action")}><AlertTriangle/>Reject & raise observation</button><button className="wf-primary" disabled={!complete(auditKeys)} onClick={()=>onAction("Approved by Auditor – Ready to Release")}>Approve for release</button></div></>;
 if(correction&&can("Accountant"))action=<><div className="wf-observation"><AlertTriangle/><div><small>AUDIT OBSERVATION RECEIVED</small><b>OBS-{Math.abs(p.id)+300}</b><p>{observation}</p><span>Assigned to Accounts · Due in 2 days</span></div></div><label className="wf-note">Accountant response<textarea placeholder="Explain what was corrected"/></label><label className="wf-proof"><Paperclip/>Upload correction proof<input type="file" onChange={e=>setProof(e.target.files?.[0]?.name||"")}/>{proof&&<b>{proof}</b>}</label><button className="wf-primary" disabled={!proof} onClick={()=>onAction("Audit Reconfirmation")}>Respond with Proof</button></>;
 if(recheck&&can("Auditor"))action=<><div className="wf-callout"><FileCheck2/>Accounts responded with correction proof. Reconfirm before approval.</div>{list(auditKeys)}<div className="wf-actions"><button className="wf-reject" onClick={()=>onAction("Observation – Accounts Action")}>Return Again</button><button className="wf-primary" disabled={!complete(auditKeys)} onClick={()=>onAction("Approved by Auditor – Ready to Release")}>Reconfirm & Approve</button></div></>;
 if(approved&&(can("Accountant")||can("Finance")))action=<><div className="wf-success"><FileCheck2/><div><b>Approved by Auditor</b><p>Upload payment/bank proof before marking this request as released.</p></div></div><label className="wf-proof"><Paperclip/>Upload release proof<input type="file" onChange={e=>setProof(e.target.files?.[0]?.name||"")}/>{proof&&<b>{proof}</b>}</label><button className="wf-primary" disabled={!proof} onClick={()=>onAction("Payment Released")}>Mark as Released</button></>;
 if(p.status==="Rejected")action=<div className="wf-observation"><AlertTriangle/><div><small>REJECTED</small><b>Sent back to the requestor</b><p>This request was rejected. The requestor can correct and raise it again.</p></div></div>;
 if(released)action=<div className="wf-success"><FileCheck2/><div><b>Payment Released</b><p>Release proof and the complete approval history are retained.</p></div></div>;
 if(role==="Requestor"||role==="Payment Requestor")action=<div className="wf-callout"><Clock3/>Status-only access. Accounts and Audit actions are hidden.</div>;
 const title=accountQueue?"Accounts acceptance":accountWork?"Accountant verification":auditQueue?"Audit acceptance":auditWork?"Audit verification":correction?"Respond to audit observation":recheck?"Audit reconfirmation":approved?"Upload proof & release":"Completed";
 return <><button className="overlay" onClick={onClose}/><aside className="detail workflow-detail"><header><div><small>PAYMENT CONTROL · {role.toUpperCase()}</small><h2>{p.requestNo}</h2></div><button onClick={onClose}><X/></button></header><div className="detail-body"><div className="wf-summary"><div><span className="badge blue">{p.status}</span><h3>{p.vendor}</h3><b className="amount">{p.currency} {p.amount.toLocaleString()}</b></div><dl><div><dt>Company</dt><dd>{p.company}</dd></div><div><dt>Department</dt><dd>{p.department}</dd></div><div><dt>Due</dt><dd>{p.due}</dd></div><div><dt>Owner</dt><dd>{p.owner}</dd></div></dl></div><div className="wf-stage">{stages.map((s,i)=><div className={i<active?"past":i===active?"now":""} key={s}><i>{i<active?<Check/>:i+1}</i><span>{s}</span></div>)}</div><section className="wf-work"><div className="wf-title"><div><small>CURRENT ACTION</small><h4>{title}</h4></div><span className="badge amber">{role}</span></div>{action}</section><Attachments entityType="payment" entityId={String(p.id)} flash={()=>{}}/><section className="wf-history"><h4>Controlled audit trail</h4>{["Request submitted with documents","Accounts and Audit acceptance recorded","Checklist, observation, response and proof retained"].map((x,i)=><p key={x}><i/><span><b>{x}</b><small>{i?"Recorded at each action":"Today · Requestor"}</small></span></p>)}</section></div></aside></>
}
